-- MySQL Script generated by MySQL Workbench
-- ter 05 nov 2019 20:24:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HomeTasks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HomeTasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HomeTasks` DEFAULT CHARACTER SET utf8 ;
USE `HomeTasks` ;

-- -----------------------------------------------------
-- Table `HomeTasks`.`Casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Casa` (
  `idCasa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `aluguel` DECIMAL(6,2) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCasa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Usuario` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `pontos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `idCasa` INT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Casa1_idx` (`idCasa` ASC),
  CONSTRAINT `fk_Usuario_Casa1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `HomeTasks`.`Casa` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Tarefa` (
  `idTarefa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `idRelator` VARCHAR(45) NOT NULL,
  `idResponsavel` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefa_Usuario1_idx` (`idRelator` ASC),
  INDEX `fk_Tarefa_Usuario2_idx` (`idResponsavel` ASC),
  CONSTRAINT `fk_Tarefa_Usuario1`
    FOREIGN KEY (`idRelator`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefa_Usuario2`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Pagamento` (
  `idCredor` VARCHAR(45) NOT NULL,
  `idDevedor` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `juros` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCredor`, `idDevedor`),
  INDEX `fk_Usuario_has_Usuario_Usuario2_idx` (`idDevedor` ASC),
  INDEX `fk_Usuario_has_Usuario_Usuario1_idx` (`idCredor` ASC),
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`idCredor`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario2`
    FOREIGN KEY (`idDevedor`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(255) NOT NULL,
  `midia` BLOB NULL,
  `data` DATETIME NOT NULL,
  `idTarefa` INT NOT NULL,
  `idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComentario`, `idTarefa`, `idUsuario`),
  INDEX `fk_Comentario_Tarefa1_idx` (`idTarefa` ASC),
  INDEX `fk_Comentario_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Comentario_Tarefa1`
    FOREIGN KEY (`idTarefa`)
    REFERENCES `HomeTasks`.`Tarefa` (`idTarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Regra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Regra` (
  `idRegra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  `idUsuario` VARCHAR(45) NOT NULL,
  `idCasa` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegra`, `idCasa`),
  INDEX `fk_Regra_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Regra_Casa1_idx` (`idCasa` ASC),
  CONSTRAINT `fk_Regra_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Regra_Casa1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `HomeTasks`.`Casa` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Rotina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Rotina` (
  `validade` DATE NOT NULL,
  `alternar` BIT NOT NULL,
  `idRotina` INT NOT NULL,
  PRIMARY KEY (`idRotina`),
  CONSTRAINT `fk_Rotina_Tarefa1`
    FOREIGN KEY (`idRotina`)
    REFERENCES `HomeTasks`.`Tarefa` (`idTarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Aprova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Aprova` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `idRegra` INT NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRegra`),
  INDEX `fk_Usuario_has_Regra_Regra2_idx` (`idRegra` ASC),
  INDEX `fk_Usuario_has_Regra_Usuario2_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Regra_Usuario2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Regra_Regra2`
    FOREIGN KEY (`idRegra`)
    REFERENCES `HomeTasks`.`Regra` (`idRegra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`Convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`Convite` (
  `idConvidado` VARCHAR(45) NOT NULL,
  `idConvidante` VARCHAR(45) NOT NULL,
  `sentido` BIT NOT NULL,
  `estado` BIT NOT NULL,
  `idCasa` INT NOT NULL,
  PRIMARY KEY (`idConvidado`, `idConvidante`, `idCasa`),
  INDEX `fk_Usuario_has_Usuario_Usuario5_idx` (`idConvidante` ASC),
  INDEX `fk_Usuario_has_Usuario_Usuario4_idx` (`idConvidado` ASC),
  INDEX `fk_Usuario_has_Usuario_Casa1_idx` (`idCasa` ASC),
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario4`
    FOREIGN KEY (`idConvidado`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario5`
    FOREIGN KEY (`idConvidante`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Casa1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `HomeTasks`.`Casa` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeTasks`.`UsuarioRotina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HomeTasks`.`UsuarioRotina` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `idRotina` INT NOT NULL,
  `data` DATE NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRotina`),
  INDEX `fk_Usuario_has_Rotina_Rotina1_idx` (`idRotina` ASC),
  INDEX `fk_Usuario_has_Rotina_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Rotina_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `HomeTasks`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Rotina_Rotina1`
    FOREIGN KEY (`idRotina`)
    REFERENCES `HomeTasks`.`Rotina` (`idRotina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
